apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: dp-vaktmester-mellomlagring
  namespace: teamdagpenger
  labels:
    team: teamdagpenger
spec:
  image: "{{ image }}"
  port: 8080
  liveness:
    path: /isalive
  readiness:
    path: /isready
  prometheus:
    enabled: true
    path: /metrics
  replicas:
    min: 1
    max: 1
  kafka:
    pool: "{{ KAFKA_POOL }}"
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
  secureLogs:
    enabled: true
  azure:
    application:
      enabled: true
  accessPolicy:
    outbound:
      rules:
        - application: dp-mellomlagring
  env:
    - name: DP_MELLOMLAGRING_SCOPE
      value: "{{ DP_MELLOMLAGRING_SCOPE }}"
  observability:
    logging:
      destinations:
        - id: loki
        - id: elastic
    autoInstrumentation:
      enabled: true
      runtime: java
